name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build: 
    runs-on: ${{build-config['os']}}
    strategy: 
      matrix:
        build-config: 
          - {os : 'ubuntu-latest', testdir: 'test'}
          - {os : 'windows-latest', testdir: 'test/${{env.BUILD_TYPE}}'}
          - {os : 'macOS-latest', testdir: 'test'}
    
    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DSPIDA_TEST::BOOL=1 

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Spida test
      working-directory: ${{github.workspace}}/build
      run:  ./${{build-config['testdir']}}/spidatest 
        
      
